### ISSUE TITLE
For the language script; only return repositories where the language specified is the default (primary) language 

### ISSUE THREAD

**Issue by NickLiffen** [NickLiffen/ghas-enablement#11]
As an org admin (or team admin) running this script, the language script can be quite broad and return repositories where the language is only used across 1% of the repository, this is inefficient and not relevant. I would like only to return the languages that are primary, so I know the pull requests I create can be targeted and precise.

**Comment by NickLiffen** [comment]
@ataylorme I know you had some interest in this 👍

**Comment by NickLiffen** [comment]
This is an example query that could get that information:

```graphql
query searchByAllReposFindingPrimaryLanguage($login: String!) {
  organization(login: $login) {
    repositories(first: 100) {
      totalCount
      nodes {
        primaryLanguage {
          name
        }
        name
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
```

I guess the problem here is it would have to loop through **every** repo. It would be nice to find a way to look through languages where the default language is `X` and it returns the repository, not the other way around.

**Comment by NickLiffen** [comment]
> I guess the problem here is it would have to loop through **every** repo. It would be nice to find a way to look through languages where the default language is `X` and it returns the repository, not the other way around.

I am sure this is possible, just need some digging into the API.

**Comment by ataylorme** [comment]
@NickLiffen digging into GitHub search I believe this is the existing behavior of your code as [you are using the search API with the `languages` filter](https://github.com/NickLiffen/ghas-enablement/blob/1ecf3a47ca3170ce4506b7905d40413b31016067/src/utils/getRepoByLanguage.ts#L17:L21)

The language filter in search queries only returns repos with that language as the primary language, not repos with that language anywhere in them.

For example, [this search for my repos with the language `css`](https://github.com/search?q=user%3Aataylorme+org%3Aataylorme+language%3Acss) returns 1 result even though a majority of my repos have at least one `.css` file in them

If you wanted to find all languages for a repo you would need to use [the `/repos/{owner}/{repo}/languages` endpoint](https://docs.github.com/en/rest/reference/repos#list-repository-languages). That endpoint returns all languages used in the repo and shows the number of bytes for each one.

Here is an example from my repo in the search result above:

```
{
  "CSS": 20487,
  "HTML": 18070,
  "JavaScript": 4360,
  "Ruby": 1216
}
```

CSS is the primary language as it has the most representation. The repo contains HTML too but [this search for my repos with the language `html`](https://github.com/search?q=user%3Aataylorme+org%3Aataylorme+language%3Acss) returns no results, proving the `language` filter in GitHub search only looks at primary language.

**Comment by NickLiffen** [comment]
@ataylorme ah amazing 🎧 I think we need to do a better job updating our docs then as it mentions "language includes" 🤦 

Thanks for raising this up 💯 I will go ahead and close this issue.
