### ISSUE TITLE
Windows having issue with the command format

### ISSUE THREAD

**Issue by tew9ey** [NickLiffen/ghas-enablement#19]
@NickLiffen 
The commands and file structures don't work so well on windows, for example, using "/" on windows gives Error: spawn C:\Windows\system32\cmd.exe ENOENT, improvement was to detect the platform in which the user works on and use "\" if it's a window or "/" if it's a mac.

- using a Desktop as a destination on a windows machine can be **ambiguous** for some **organizations like EY,** as there are several users on the enterprise machine, so to be specific, we recommend using Documents as the destination as the user will most of the time have direct access to the Documents directory. it was giving us in EY the same spawn error above.

- `{ command: "mkdir -p .github/workflows" }` was giving syntax error too, at least on windows, So I enhance it by explicitly specifying .github/workflows as string, something like this. `mkdir -p ".github/workflows"` 

- **_The two first enhancements have taken care of the spawn error in the windows machine. and the third one got rid of the syntax error. _**

**Comment by NickLiffen** [comment]
@tew9ey 👋 

right now, there are no windows commands. check this out [here](https://github.com/NickLiffen/ghas-enablement/blob/main/src/utils/commands.ts#L44). 

I don't have a Windows machine, so can't actually test out 😢 If possible I would really need someone who has a Windows machine to copy the mac commands (found [here](https://github.com/NickLiffen/ghas-enablement/blob/main/src/utils/commands.ts#L5)) and actually copy them into the[ windows commands](https://github.com/NickLiffen/ghas-enablement/blob/main/src/utils/commands.ts#L44) and replace what isn't working with Windows-specific commands. 

If possible I need someone with a windows machine to do this; as I don't have a machine to 100% test functionality.

@tew9ey I agree though; this won't work on windows right now; it just needs someone who knows the right windows commands to put them in; and then it will work.

**Comment by tew9ey** [comment]
@NickLiffen 
I agree with you, well I'll try the best I can to try to make it work for windows and will create a PR once it's done.
thank you for the clarification @NickLiffen

**Comment by NickLiffen** [comment]
Amazing @tew9ey if you could it would be AMAZING 🎧 

You are going to likely want to add a step to _check_ if the user is on a windows or mac machine; and based off that; either run the Windows or Mac commands. 

Doing a **quick** google, you could do [this](https://stackoverflow.com/questions/10527983/best-way-to-detect-mac-os-x-or-windows-computers-with-javascript-or-jquery).

Bascially what I see is a quick:

1) Detect Mac/Windows
2) If Windows -> run Windows commands
3) If Mac -> run Mac commands
4) If neither Windows **or** mac I would just maybe `throw new Error(${os} not supported right now`

> @NickLiffen can you create an enhancement issue and assign it to me and mark it as in progress?

Yes I will do that now 👍
