### ISSUE TITLE
Support Windows Commands :) 

### ISSUE THREAD

**Issue by NickLiffen** [NickLiffen/ghas-enablement#20]
As an end-user of this utility; I would like to be able to run this on Windows, and not just mac, so I can use the tool without getting errors. 

The way that I would go about implementing is:

1) Add a small function that detects the OS of the user. E.G (windows, linux, windows, etc)

2) Add the windows commands [here](https://github.com/NickLiffen/ghas-enablement/blob/main/src/utils/commands.ts#L44). 

3) Use the function that has been created in step 1) to detect what OS the end user is using. If they are using Mac, send to the mac commands, if they are using Windows, send to the Windows commands 👍 If they are using another os like Linux, etc, I would throw an error

^^^ This can be changed, this is just my thoughts, however, 100% welcome other thoughts on this if people have any 👍 **Very** open for discussions and thoughts 👍

**Comment by NickLiffen** [comment]
@tew9ey ^^^ I have invited you to collaborate on this repository 👍

**Comment by tew9ey** [comment]
thank you @NickLiffen will do the best I can and let you know If I get stuck anywhere.

**Comment by NickLiffen** [comment]
No problem 👍 once you are ready to PR please let me know and I am **more** then happy to help 👍

**Comment by tew9ey** [comment]
Hello @NickLiffen,
I have created the PR but I think the code scanning is failing on the existing code, not the newly added codes.
Let me know If you have any questions or suggestions.

**Comment by NickLiffen** [comment]
@tew9ey I am **so sorry** for not responding 😢 I had my laptop and a few things stolen so todays my first day back 💯 I will look into this first thing tomorrow if that's good with you? I will fix the security problem. I agree that isn't your code 💯 
Great work btw 👍

**Comment by tew9ey** [comment]
unfortunate to hear that @NickLiffen , hopefully it's only material lost and you're safe. It's all understood.

**Comment by NickLiffen** [comment]
Fixed in #21
