### ISSUE TITLE
Speed up git clone

### ISSUE THREAD

**Issue by agonzalez-plume** [NickLiffen/ghas-enablement#45]
I've got a modification to improve the throughput for my use case, which is just for committing a new workflow to repos. I was wondering if this change would be appreciated by others:

in src/utils/commands.ts: clone with options --depth 1, --filter=blob:none and --sparse. By cloning this way, the amount of data will be reduced. Not eliminated, but reduced. 

```
    {
      command: "git",
      args: ["clone","--depth","1","--filter=blob:none","--sparse", `${baseURL}/${owner}/${repo}.git`],
      cwd: `/Users/${user}/${destDir}/${tempDIR}`,
    },
```

These pages explain the concepts and I combined a couple. Seemed to give the smallest size and allows adding a new workflow file without issues for me.
https://unix.stackexchange.com/questions/233327/is-it-possible-to-clone-only-part-of-a-git-project
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

I can submit a PR if you think it's good. I believe new git >2.19 will support them, but didn't test any git versions except Mac git 2.32 which I am on.

**Comment by NickLiffen** [comment]
I am perfectly good with this 👍 

If you are good to make a PR, but make it specific to the `maccomands` that would be amazing 👍

**Comment by NickLiffen** [comment]
@agonzalez-plume this should now be merged in 🙇
