### ISSUE TITLE
Typescript install error

### ISSUE THREAD

**Issue by djthornton1212** [NickLiffen/ghas-enablement#54]
# Problem:
npx fails to install typescript

# System Info:
System OS: Windows
NodeJS: 17.5.0

# Logs:

> yarn run getOrgs
> yarn run v1.22.15
> $ npm run build && node ./lib/src/getOrgs.js
> 
> github-helper@1.0.0 build
> npx tsc
> 
> Need to install the following packages:
>   tsc
> Ok to proceed? (y) y
> 
> This is not the tsc command you are looking for
> 
> To get access to the TypeScript compiler, tsc, from the command line either:
> 
> - Use npm install typescript to first add TypeScript to your project before using npx
> - Use yarn to avoid accidentally running code from un-installed packages
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

# Expected behavior:
Yarn will successfully install typescript

**Comment by NickLiffen** [comment]
Hey @djthornton1212 👋 

Do you have typescript installed on your machine? 🤔 

I can't seem to replicate this 🤔 

Are you able to run it in a Codespace by any chance?

**Comment by djthornton1212** [comment]
No, it wasn't. I didn't realize it was a requirement. I manually installed it and now it's working.

**Comment by djthornton1212** [comment]
This should probably go into another issue, but it's complaining that my `repo` scope isn't enough:

> Your token has not been granted the required scopes to execute this query. The 'login' field requires one of the following scopes: ['read:org'], but your token has only been granted the: ['read:packages', 'repo', 'workflow'] scopes.

Want me to open a separate issue for the documentation change on that one?

**Comment by NickLiffen** [comment]
> No, it wasn't. I didn't realize it was a requirement. I manually installed it and now it's working.. sort of.

Thanks for the note 👍 I updated the `README.md` here: #56

**Comment by NickLiffen** [comment]
> Want me to open a separate issue for the documentation change on that one?

Fixed that #57 

Thanks so much for all this feedback 🙇

**Comment by NickLiffen** [comment]
Feel free to open more issues as you see them 👍 

Also, please feel free to raise a pull request if you feel confident 🙇

**Comment by djthornton1212** [comment]
No problem. Happy to be of assistance. I'm currently troubleshooting why the app is getting a null returned on the getOrgs. I've put it in GitHub's GraphQL explorer and it works fine. Once I figure more out I'll open a new one.

Thanks!

**Comment by NickLiffen** [comment]
If you are running `getOrgs` you will have to use a `PAT` 🙇 I don't think it will work with a GitHub App, as the GitHub App here is tied to an org 😢 

So if you want to run this across multiple orgs, use a `PAT` (I eventually want to support a github app across multiple orgs, but right now it's just a single org ❤️

**Comment by djthornton1212** [comment]
Yeah, that's what I'm doing.

I'll open a new issue with what I'm seeing.
