### ISSUE TITLE
Cannot read properties of null (reading 'organizations')

### ISSUE THREAD

**Issue by djthornton1212** [NickLiffen/ghas-enablement#58]
# Problem:
`yarn run getOrgs` returns error: `TypeError: Cannot read properties of null (reading 'organizations')`

Please excuse all the sanitation, my company's shy.

# System Info:
System OS: Windows
NodeJS: 17.5.0

# .env Config:
GITHUB_API_TOKEN=ghp_
GITHUB_ENTERPRISE=<private_company_name>

All other configs are default

# Logs:

> TypeError: Cannot read properties of null (reading 'organizations')
>     at performOrganisationsQuery (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:9:103)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async getOrganisationsInEnterprise (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:19:49)
>     at async index (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:43:22)
>     at async start (C:\Users\dthornton\code\ghas-enablement\lib\src\getOrgs.js:30:9)
>   ghas:error TypeError: Cannot read properties of null (reading 'organizations')
>   ghas:error     at performOrganisationsQuery (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:9:103)
>   ghas:error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   ghas:error     at async getOrganisationsInEnterprise (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:19:49)
>   ghas:error     at async index (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:43:22)
>   ghas:error     at async start (C:\Users\dthornton\code\ghas-enablement\lib\src\getOrgs.js:30:9) +0ms
> TypeError: Cannot read properties of null (reading 'organizations')
>     at performOrganisationsQuery (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:9:103)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async getOrganisationsInEnterprise (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:19:49)
>     at async index (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:43:22)
>     at async start (C:\Users\dthornton\code\ghas-enablement\lib\src\getOrgs.js:30:9)
>   ghas:error TypeError: Cannot read properties of null (reading 'organizations')
>   ghas:error     at performOrganisationsQuery (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:9:103)
>   ghas:error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   ghas:error     at async getOrganisationsInEnterprise (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:19:49)
>   ghas:error     at async index (C:\Users\dthornton\code\ghas-enablement\lib\src\utils\getOrganisationsInEnterprise.js:43:22)
>   ghas:error     at async start (C:\Users\dthornton\code\ghas-enablement\lib\src\getOrgs.js:30:9) +2ms
> Done in 5.71s.

# Expected behavior:
Returned organizations from Enterprise query

Please note that I copied the query into GitHub GraphQL Explorer and it returns the organizations as expected.

```
{
  "data": {
    "viewer": {
      "login": "djthornton1212"
    },
    "rateLimit": {
      "limit": 5000,
      "cost": 1,
      "remaining": 4989,
      "resetAt": "2022-04-07T19:23:33Z",
      "used": 11
    },
    "enterprise": {
      "organizations": {
        "nodes": [
          {
            "login": "<1st org>"
          },
          {
            "login": "<2nd org>"
          }
        ],
        "totalCount": 2,
        "pageInfo": {
          "hasNextPage": false,
          "endCursor": "Y3Vyc29yOnYyOpKuQ2FyZWdpbGl0eS1GZWTOBdckCA=="
        }
      }
    }
  }
}
```

**Comment by djthornton1212** [comment]
Does it matter that everything in the organization's private?

I would imagine that the PAT would be enough. I have admin access to the enterprise and used the repo scope.

**Comment by NickLiffen** [comment]
Thanks for logging 🙇 

Is this on GHEC I assume? :) As you are using the explore? This isn't a server instance? This is on github.com/xxx :)

**Comment by djthornton1212** [comment]
Correct. It's GHEC.

**Comment by NickLiffen** [comment]
Okay 👍 give me some time to debug this 🤔 I just quickly tested and it worked. 

Just making sure you are putting in the right enterprise? This is case sensitive so make sure you are entering the right enterprise and it's in the right case 👍

**Comment by djthornton1212** [comment]
Yeah, I double checked that. At first it was wrong as GitHub has it as `<name>-trail`. I fixed that in the explorer and it worked fine.

**Comment by djthornton1212** [comment]
I'm not a javascript developer, but the typescript -> javascript is confusing. However, I think I've narrowed it down to [here](https://github.com/NickLiffen/ghas-enablement/blob/4bed1ab185ea8a762c418591a619ca2ec8752710/src/utils/getOrganisationsInEnterprise.ts#L20). I'm not getting to the return.

**Comment by djthornton1212** [comment]
Ok, I figured it out. 

Turns out that in order to read the enterprise's organizations the PAT needs at least `read:enterprise`:
![image](https://user-images.githubusercontent.com/99346713/162337171-d6e24b25-11a9-482b-8e95-c2b2df74fd5f.png)
🤦‍♂️

**Comment by NickLiffen** [comment]
Ah, @djthornton1212 😮‍💨 I'm so sorry that wasn't documented 😢 

Thank you for sharing how to fix that 🙇 

I have gone ahead and updated the `README.md` here: #59 ❤️

**Comment by djthornton1212** [comment]
Thanks, it was an interesting exercise troubleshooting.
