### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shreenivas-asurion** [NickLiffen/ghas-enablement#68]
I am trying to build this first time and I am getting the below error.
src/utils/worker.ts:27:39 - error TS2339: Property 'length' does not exist on type '{}'.

27   for (orgIndex = 0; orgIndex < repos.length; orgIndex++) {

Do I need to prefil the repos file? I thought the app does that and then I can run the npm run start? 

I am running on MacOS, not sure if that is an issue. I had to do npm install --force to npm install it.

**Comment by shreenivas-asurion** [comment]
@NickLiffen forgot to tag you. 
node --version
v16.13.1

**Comment by ajilty** [comment]
I needed at least one repo in that file to make it work now and the element repos.enablePushProtection needed to be included.

**Comment by NickLiffen** [comment]
I just raised #70 which should fix this 👍 Sorry for the problems 🙇

**Comment by shreenivas-asurion** [comment]
Awesome, this looks good. Thanks. #70  👍
