### ISSUE TITLE
yarn run build fails on initial clone

### ISSUE THREAD

**Issue by felickz** [NickLiffen/ghas-enablement#71]
yarn run build fails on initial clone

Creating repos.json is not optional - required for build

**Comment by NickLiffen** [comment]
Thanks @felickz for raising this 🙇 

Did you see within this section: [What does this tooling do?](https://github.com/NickLiffen/ghas-enablement#what-does-this-tooling-do), it says this: `Manually create repos.json or rename repos-sample.json -> repos.json in the bin folder.`. 

The `repos.json` is not optional, correct 🙇 

If you think this can be made clearer, please feel free to raise a pull request, I would love your input on what can be done to make it better ❤️

**Comment by felickz** [comment]
Hmm no, I thought I searched the docs to verify 😒

I fully intended to follow up with this and not leave an empty issue - sorry!
