### ISSUE TITLE
GitHub App token times out after 1 hour

### ISSUE THREAD

**Issue by djredman99** [NickLiffen/ghas-enablement#77]
The current implementation is limited with regards to the use of a GitHub App to serve as the identity, and the default timeout (60 minutes) of the JWT token returned by ocktokit for the GitHub App to authenticate with. 

For longer running batches that will last more than 1 hour, the token will expire and start failing the subsequent API calls being made.

**Comment by NickLiffen** [comment]
@djredman99 👋 

Just to clarify, are you saying after 60 minutes the token doesn't refresh (as it should do this taking a look at the code 👀)

Or, are you saying you are making 1 request that takes longer than 60 minutes? E.G a `clone` is taking 60 minutes? 

I am going to _guess_ it's the 1st point. If so, I will try and manually reset it _if_ it's timing out in the next 5 minutes 👍

**Comment by djredman99** [comment]
@NickLiffen 

That is the experience they are getting...after 60 minutes the token is not refreshing and they start to receive timeout messaging.

**Comment by djredman99** [comment]
Going to close this as the issue seems to be resolved in PR #79
