### ISSUE TITLE
https 404 Error

### ISSUE THREAD

**Issue by basel-ui** [NickLiffen/ghas-enablement#85]
Hi Nick,

i have some issues with the npm run start command. There give me back that they have no access to the url what i written in the .env file. Can you help me with them ? I have added the errormessage and the .env file

**Comment by NickLiffen** [comment]
In your `.env` you have two `ENABLE_ON` could you remove one of them, as such it's this:

```
ENABLE_ON=codescanning,secretscanning
```

(just to test it on these two please 🙇) 

And just to triple check, you ran `npm run getRepos` firstly, and that ran successfully, correct? 

Could you update the `.env` with the above value (`ENABLE_ON=codescanning,secretscanning`, re-run `npm run getRepos` and then run `npm run start` again please 🙇 

Can you also make sure the PAT has the right scopes. E.G `repo, workflow and read:org` 🙇

**Comment by basel-ui** [comment]
Hi Nick,

first of all thank you for the fast answer 😄 

i have made the changes and i get the same error. Yeah for sure, i set the command npm run getRepos first, it also successfully gives me the repos.json with the collected repos.

**error-message:** 
$ npm run getRepos
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> github-helper@1.0.0 getRepos
> npm run build && node ./lib/getRepos.js

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> github-helper@1.0.0 build
> npx tsc

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
  ghas:inform Could not find file: ./bin/organizations.json. Assuming no organizations have been collected. +0ms
  ghas:inform Collecting repositories for ghas-playground +1ms
  ghas:inform This is org number 1 of 1 +1ms
  ghas:inform Repo Name: ghas-playground/super-octo-waddle Permission: ADMIN Archived: false Language: JavaScript Visibility: INTERNAL +815ms
  ghas:inform Repo Name: ghas-playground/configure-jfrog-cli Permission: ADMIN Archived: false Language: no-language Visibility: PUBLIC +1ms
  ghas:inform Repo Name: ghas-playground/xray-actions Permission: ADMIN Archived: false Language: Python Visibility: PUBLIC +0ms
  ghas:inform Repo Name: ghas-playground/ghas-basel-playground Permission: ADMIN Archived: false Language: no-language Visibility: PRIVATE +1ms
  ghas:inform Repo Name: ghas-playground/ghas-enablement-1 Permission: ADMIN Archived: false Language: no-language 
Visibility: PUBLIC +0ms
  ghas:inform Repo Name: ghas-playground/ghas-enablement-2 Permission: ADMIN Archived: false Language: no-language 
Visibility: PUBLIC +1ms
  ghas:inform Repo Name: ghas-playground/ghas-enablement Permission: ADMIN Archived: false Language: TypeScript Visibility: PUBLIC +0ms
  ghas:inform Repo Name: ghas-playground/basel-playground Permission: ADMIN Archived: false Language: no-language Visibility: PUBLIC +1ms
  ghas:inform Repo Name: ghas-playground/ghas-enablement_ruby Permission: ADMIN Archived: false Language: C Visibility: PUBLIC +1ms
  ghas:inform Repo Name: ghas-playground/ghas_enablement_java Permission: ADMIN Archived: false Language: JavaScript Visibility: PUBLIC +1ms
  ghas:inform Repo Name: ghas-playground/ghas-enablement-python Permission: ADMIN Archived: false Language: Python 
Visibility: PUBLIC +0ms
  ghas:inform Found 1 repositories that met the valid criteria in the organisation ghas-playground. Out of 11. +1ms  ghas:inform All repos collected. Writing them to file: ./bin/repos.json +1ms
  ghas:inform Success created repos.json +1ms

bsalem@TAG-0797 MINGW64 ~/Documents/GitHub/ghas-enablement (main)
$ npm run start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> github-helper@1.0.0 start
> npm run build && node ./lib/enable.js

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> github-helper@1.0.0 build
> npx tsc

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
  ghas:inform Platform detected: win32 +0ms
  ghas:inform Currently looping over: 1/1. The org name is: ghas-playground +8ms
  ghas:inform Currently looping over: 1/1. The repo name is: ghas-playground/ghas-enablement +2ms
  ghas:inform Enabled GHAS for ghas-enablement. Status: 200 +626ms
  ghas:inform Enabled Secret Scanning for ghas-enablement. Status: 200 +987ms
  ghas:inform Has ghas-playground/ghas-enablement had a CodeQL scan uploaded? false +2s
  ghas:inform Has ghas-playground/ghas-enablement hasn't had a CodeQL Scan, going to run CodeQL enablement +1ms
  ghas:inform Found default branch on the following repository: ghas-enablement. The default branch is: main +576ms  ghas:error Problem finding default branch SHA on the following repository: ghas-enablement. The error was: HttpError: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
  ghas:error <html><head>
  ghas:error <title>404 Not Found</title>
  ghas:error </head><body>
  ghas:error <h1>Not Found</h1>
  ghas:error <p>The requested URL was not found on this server.</p>
  ghas:error </body></html>
  ghas:error  +0ms
  ghas:error HttpError: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
  ghas:error <html><head>
  ghas:error <title>404 Not Found</title>
  ghas:error </head><body>
  ghas:error <h1>Not Found</h1>
  ghas:error <p>The requested URL was not found on this server.</p>
  ghas:error </body></html>
  ghas:error 
  ghas:error     at C:\Users\bsalem\Documents\GitHub\ghas-enablement\node_modules\@octokit\request\dist-node\index.js:86:21
  ghas:error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ghas:error     at async Job.doExecute (C:\Users\bsalem\Documents\GitHub\ghas-enablement\node_modules\bottleneck\light.js:405:18) +2ms
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RequestError [HttpError]: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

    at C:\Users\bsalem\Documents\GitHub\ghas-enablement\node_modules\@octokit\request\dist-node\index.js:86:21     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (C:\Users\bsalem\Documents\GitHub\ghas-enablement\node_modules\bottleneck\light.js:405:18) {
  status: 404,
  response: {
    url: 'https://git.dev.hub.vwgroup.com/api/v3/repos/ghas-playground/ghas-enablement/git/ref/heads%2Fmain',      
    status: 404,
    headers: {
      connection: 'close',
      'content-length': '196',
      'content-type': 'text/html; charset=iso-8859-1',
      date: 'Wed, 03 Aug 2022 13:09:49 GMT',
      server: 'Apache',
      'strict-transport-security': 'max-age=15768000; includeSubDomains'
    },
    data: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' +
      '<html><head>\n' +
      '<title>404 Not Found</title>\n' +
      '</head><body>\n' +
      '<h1>Not Found</h1>\n' +
      '<p>The requested URL was not found on this server.</p>\n' +
      '</body></html>\n'
  },
  request: {
    method: 'GET',
    url: 'https://git.dev.hub.vwgroup.com/api/v3/repos/ghas-playground/ghas-enablement/git/ref/heads%2Fmain',      
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/16.16.0 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      retries: 3,
      hook: [Function: bound bound register],
      retryCount: 3
    }
  }
}

**Comment by NickLiffen** [comment]
@basel-ui 👋 question, is this an empty repo, Have there ever been any commits to this repository before? 🤔

**Comment by NickLiffen** [comment]
@basel-ui I see you closed this out, I would love to know if this is working for you/if you need anything else from me?

**Comment by basel-ui** [comment]
Yeah please, can you Delete my Ticket?
Thank you!
