### ISSUE TITLE
Just a minor typo

### ISSUE THREAD

**Issue by elihu** [NickLiffen/ghas-enablement#90]
Hi! just having a look at the code, found this minor typo. It really doesn't seems to affect functionality but just for let you know

https://github.com/NickLiffen/ghas-enablement/blob/b0af11dc7fd600808ac8e171511bc0e19390f147/types/common/index.d.ts#L2

Thanks for the tool, very useful!

**Comment by NickLiffen** [comment]
Just fixed here: https://github.com/NickLiffen/ghas-enablement/commit/36817247066501c834cf0f3ddf86b214484a2f2d ❤️ 

Thank you for the call out ❤️
