### ISSUE TITLE
Missing codeql-analysis.yaml file in root of repo

### ISSUE THREAD

**Issue by benhorgen** [NickLiffen/ghas-enablement#94]
The README.md says in **PART 2** that "A pull request gets created on that repository with the `codeql-analysis.yml` found in the root of this repository." I am not seeing that `codeql-analysis.yml` file in the root of the this repo.

**Comment by NickLiffen** [comment]
Fixed here: https://github.com/NickLiffen/ghas-enablement/pull/95

Thanks @benhorgen ❤️
