### ISSUE TITLE
How to apply the CodeQL to a repo without a Pull Request?

### ISSUE THREAD

**Issue by benhorgen** [NickLiffen/ghas-enablement#96]
I thought there was a way to run the script and toggle Code Scanning to be enabled without requiring a PR approval. Can anyone remind me the setting in the `.env` or `repos.json` config files to make the enablement  and the commit of the `.github/worksflows/codeql.yml` happen upon execution of the script?

**Comment by NickLiffen** [comment]
Hey 👋 

You can do this in code scanning today 👍 you would just need to upload the `codeql-analysis.yml` file to the default branch 👍 versus having it done via a pull request. 

There is a feature request to merge the pull request automatically, but I haven't gotten around to making that PR yet 😢 I would love someone to take a stab at it though. 

I still think we should do the pull request, but just automatically merge it, versus going straight in. It would give the same experience, but there is better traceability versus the PR.

**Comment by john-yacuta-submittable** [comment]
Hi @NickLiffen, I noticed this issue is closed and was having the same question. Can you link where that feature request is to keep track of it? Is this supported yet? I would also prefer to update repos in bulk without having to manually approve and then merge PRs. Thanks!
